### ISSUE TITLE
Shouldn't we be issuing a cookie instead of a JSON response?

### ISSUE THREAD

**Issue by georgiosd** [nbarbettini/SimpleTokenProvider#26]
Hi!

I saw you recommendation in the article to use cookies instead of local storage or whatever else to keep the token - but the server returns the token as JSON by default.

Is this because the exercise is left to the reader or am I missing something?

If I understand correctly, I would take the `access_token` from the JSON response and put it in a cookie with the same name.

Thanks!

**Comment by nbarbettini** [comment]
Hi @georgiosd!

Yes, it's left as an exercise to the reader. If the app is rendering pages server-side, it's pretty easy to use ASP.NET to send a (Secure, HTTPOnly) cookie back with the response.

I need to make this less confusing - thanks for pointing it out. Let me know if you need further clarification.

**Comment by georgiosd** [comment]
No problem, just thought I'd check in case I'm missing anything.

Why do you say "if the app is rendering pages server-side"? I mean, It's an angular2 app but AFAIK the cookies get sent to XHR requests also, right?

**Comment by nbarbettini** [comment]
Sorry for the delay, I've been traveling.

Yes, you're right. My current preference is to use cookies for server-rendered pages and SPA (as you described). Returning tokens in the body can work for mobile apps, since cookies can be problematic there.

(I've been digging into OpenID Connect more recently, because it standardizes some of these flows in a better way than OAuth2. I think I need to write a new post that describes the differences and has some new recommendations. You're on the right track though!)

**Comment by georgiosd** [comment]
Thanks! I was making sure I'm not missing something and it looks like I'm not after all :)

Looking forward to your new post and thank you for your previous ones, they have been helpful.
