### ISSUE TITLE
Login URL

### ISSUE THREAD

**Issue by Sn3b** [nbarbettini/SimpleTokenProvider#8]
Hey,

Forgive my noobness, just trying out this nice piece of code to try to understand JWT authentication better, and I see in your test project that when trying to access a protected route I get redirected to /Account/Login?ReturnUrl=%2Fapi%2Fvalues%2F5, where is that set? I'd like to set a custom URL there...

Thanks :)

**Comment by Sn3b** [comment]
I've found that the following can be used for cookies

```
        app.UseCookieAuthentication(` new CookieAuthenticationOptions
        {
            LoginPath = "/mycustompath"
        } );
```

But what if I don't want to use cookies, can I redirect to a custom URL?

**Comment by nbarbettini** [comment]
Hi @Sn3b! You're right, that redirect behavior is associated with the cookie authentication middleware.

How are you using tokens in your application? If you are passing tokens in headers, you typically would return a `401 Unauthorized` response rather than doing a redirect. (In fact, that's exactly what the `JwtBearerAuthentication` middleware does)

**Comment by Sn3b** [comment]
Yes that's what I did, works fine, thanks! :)
