### ISSUE TITLE
NuGet Requrest

### ISSUE THREAD

**Issue by arruw** [nbarbettini/SimpleTokenProvider#9]
This looks handy... can you create NuGet package?

Anyone using this in production? And what are possible pitfalls?

Thanks and good work!

**Comment by nbarbettini** [comment]
I haven't had time recently to maintain or update this example, but I will consider publishing it as a NuGet package in the future. 👍

**Comment by nbarbettini** [comment]
Since this code is meant to be a starting point/technical example, I'm not going to publish it as a NuGet package at the moment. If you want a full-fledged solution, I'd recommend [OpenIddict](https://github.com/openiddict) or [OpenIdConnect.Server](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server).
